# Generated by Django 5.2.4 on 2025-10-07 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(help_text='The main title on the hero banner.', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, help_text='A short subtitle or motto.', max_length=500, null=True)),
                ('hero_image', models.ImageField(help_text='Recommended size: 1920x800 pixels.', upload_to='homepage/')),
                ('principals_welcome_title', models.CharField(default='A Welcome from the Principal', max_length=200)),
                ('principals_welcome_message', models.TextField(help_text='A short welcome message for the home page.')),
                ('principals_photo', models.ImageField(help_text='A portrait photo of the principal.', upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(default='Your CBSE School Name', max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
