# Generated by Django 5.2.4 on 2025-10-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carouselimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.RenameField(
            model_name='carouselimage',
            old_name='title',
            new_name='hero_title',
        ),
    ]
