# Generated by Django 5.2.4 on 2025-10-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_carouselimage_hero_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='hero_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='carouselimage',
            old_name='hero_title',
            new_name='title',
        ),
    ]
