# Generated by Django 5.2.4 on 2025-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_hero_image_carouselimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title',
            field=models.CharField(blank=True, help_text='The main title on the hero banner.', max_length=255, null=True),
        ),
    ]
