# Generated by Django 5.2.4 on 2025-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_homepagecontent_hero_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1920x800 pixels.', null=True, upload_to='homepage/'),
        ),
    ]
