# Generated by Django 5.2.4 on 2025-10-07 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(help_text='A professional headshot.', upload_to='faculty_photos/')),
                ('designation', models.CharField(help_text='e.g., Principal, TGT Mathematics, Librarian', max_length=100)),
                ('qualification', models.CharField(help_text='e.g., M.Sc. in Physics, B.Ed.', max_length=200)),
                ('department', models.CharField(help_text='e.g., Science, Humanities, Administration', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short biography or message.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display on the page (0 is first).')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
