# Generated by Django 5.2.4 on 2025-10-14 04:21

import admissions.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING_PAYMENT', max_length=20)),
                ('academic_year', models.CharField(choices=[('2025-26', '2025-26')], max_length=10)),
                ('admission_class', models.CharField(choices=[('PLAYGROUP', 'PLAY GROUP'), ('PRENURSERY', 'PRE-NURSERY'), ('NURSERY', 'NURSERY'), ('PREP', 'PREP'), ('II', 'II'), ('III', 'III'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=5, null=True)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('EWS', 'EWS'), ('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('STAFF', 'STAFF')], max_length=10)),
                ('religion', models.CharField(choices=[('HINDU', 'Hindu'), ('ISLAM', 'Islam'), ('SIKHISM', 'Sikhism'), ('CHRISTIANITY', 'Christianity'), ('BUDDHISM', 'Buddhism'), ('JAINISM', 'Jainism'), ('OTHERS', 'Others')], max_length=20)),
                ('is_single_parent', models.BooleanField(default=False)),
                ('primary_contact_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('student_type', models.CharField(choices=[('DAY SCHOLAR', 'Day scholar'), ('HOSTEL', 'hostel')], max_length=20)),
                ('nationality', models.CharField(choices=[('INDIAN', 'Indian'), ('NEPALESE', 'Nepalese'), ('OTHER', 'Other')], max_length=50)),
                ('student_photo', models.ImageField(upload_to='student_photos/', validators=[admissions.validators.validate_file_size])),
                ('previous_school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('is_interested_in_competitive_exams', models.BooleanField(default=False)),
                ('is_physically_handicapped', models.BooleanField(default=False)),
                ('pen_number', models.CharField(blank=True, max_length=50, null=True)),
                ('wants_transportation', models.BooleanField(default=False)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_annual_income', models.CharField(blank=True, max_length=50, null=True)),
                ('father_photo', models.ImageField(upload_to='parent_photos/', validators=[admissions.validators.validate_file_size])),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_photo', models.ImageField(upload_to='parent_photos/', validators=[admissions.validators.validate_file_size])),
                ('corresponding_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('number_of_daughters', models.PositiveIntegerField(default=0)),
                ('number_of_sons', models.PositiveIntegerField(default=0)),
                ('sibling_details', models.TextField(blank=True, null=True)),
                ('media_permission_facility', models.BooleanField(default=False)),
                ('media_permission_online', models.BooleanField(default=False)),
                ('media_permission_print', models.BooleanField(default=False)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/')),
                ('previous_marksheet', models.FileField(blank=True, null=True, upload_to='documents/marksheets/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='documents/tc/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
