# Generated by Django 5.2.4 on 2025-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
