# Generated by Django 5.2.4 on 2025-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
